#pragma checksum "ChecklistWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "BFFD5F3EED2BB76A3719E312D628BAA8D39A67D3C0A228D11B05F20CDD86A3D4"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Scanner {
    
    
    /// <summary>
    /// ChecklistWindow
    /// </summary>
    public partial class ChecklistWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 49 "ChecklistWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ExportButton;
        
        #line default
        #line hidden
        
        
        #line 50 "ChecklistWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ExportSimplifiedButton;
        
        #line default
        #line hidden
        
        
        #line 51 "ChecklistWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ExportCurrentMonthButton;
        
        #line default
        #line hidden
        
        
        #line 56 "ChecklistWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid StatusSummaryDataGrid;
        
        #line default
        #line hidden
        
        
        #line 61 "ChecklistWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn CurrentMonthColumn;
        
        #line default
        #line hidden
        
        
        #line 62 "ChecklistWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn PreviousMonthColumn;
        
        #line default
        #line hidden
        
        
        #line 63 "ChecklistWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn TwoMonthsAgoColumn;
        
        #line default
        #line hidden
        
        
        #line 77 "ChecklistWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock BaseStatusTextBlock;
        
        #line default
        #line hidden
        
        
        #line 78 "ChecklistWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock BaseFileTextBlock;
        
        #line default
        #line hidden
        
        
        #line 82 "ChecklistWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SnStatusTextBlock;
        
        #line default
        #line hidden
        
        
        #line 83 "ChecklistWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SnFileTextBlock;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Scanner;component/checklistwindow.xaml", System.UriKind.Relative);
            
            #line 1 "ChecklistWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 47 "ChecklistWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ImportBaseDataButton_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            
            #line 48 "ChecklistWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ImportSnButton_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.ExportButton = ((System.Windows.Controls.Button)(target));
            
            #line 49 "ChecklistWindow.xaml"
            this.ExportButton.Click += new System.Windows.RoutedEventHandler(this.ExportButton_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.ExportSimplifiedButton = ((System.Windows.Controls.Button)(target));
            
            #line 50 "ChecklistWindow.xaml"
            this.ExportSimplifiedButton.Click += new System.Windows.RoutedEventHandler(this.ExportSimplifiedButton_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.ExportCurrentMonthButton = ((System.Windows.Controls.Button)(target));
            
            #line 51 "ChecklistWindow.xaml"
            this.ExportCurrentMonthButton.Click += new System.Windows.RoutedEventHandler(this.ExportCurrentMonthButton_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.StatusSummaryDataGrid = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 7:
            this.CurrentMonthColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 8:
            this.PreviousMonthColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 9:
            this.TwoMonthsAgoColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 10:
            this.BaseStatusTextBlock = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.BaseFileTextBlock = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 12:
            this.SnStatusTextBlock = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.SnFileTextBlock = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

