#pragma checksum "MeterModelSelectionWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "7581623BB75B66F26A2088356640662186CB6551C5B2BFE8716CC3ADCD0E2012"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Scanner {
    
    
    /// <summary>
    /// MeterModelSelectionWindow
    /// </summary>
    public partial class MeterModelSelectionWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 66 "MeterModelSelectionWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox ModelListBox;
        
        #line default
        #line hidden
        
        
        #line 91 "MeterModelSelectionWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox NewModelTextBox;
        
        #line default
        #line hidden
        
        
        #line 118 "MeterModelSelectionWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock StatusTextBlock;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Scanner;component/metermodelselectionwindow.xaml", System.UriKind.Relative);
            
            #line 1 "MeterModelSelectionWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 11 "MeterModelSelectionWindow.xaml"
            ((Scanner.MeterModelSelectionWindow)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Window_Loaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.ModelListBox = ((System.Windows.Controls.ListBox)(target));
            
            #line 74 "MeterModelSelectionWindow.xaml"
            this.ModelListBox.KeyDown += new System.Windows.Input.KeyEventHandler(this.ModelListBox_KeyDown);
            
            #line default
            #line hidden
            
            #line 75 "MeterModelSelectionWindow.xaml"
            this.ModelListBox.MouseDoubleClick += new System.Windows.Input.MouseButtonEventHandler(this.ModelListBox_MouseDoubleClick);
            
            #line default
            #line hidden
            return;
            case 3:
            this.NewModelTextBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 98 "MeterModelSelectionWindow.xaml"
            this.NewModelTextBox.KeyDown += new System.Windows.Input.KeyEventHandler(this.NewModelTextBox_KeyDown);
            
            #line default
            #line hidden
            return;
            case 4:
            
            #line 110 "MeterModelSelectionWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AddAndPrintButton_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.StatusTextBlock = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            
            #line 121 "MeterModelSelectionWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.UseSelectedButton_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

