<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Scanner.Server.BLL\Scanner.Server.BLL.csproj" />
    <ProjectReference Include="..\Scanner.Server.DAL\Scanner.Server.DAL.csproj" />
    <ProjectReference Include="..\Scanner.Server.Model\Scanner.Server.Model.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="appsettings.Local.json" CopyToOutputDirectory="Never" CopyToPublishDirectory="Never" />
    <Content Update="dotnet-tools.json;README.md;App_Data\**\*;Database\**\*;wwwroot\register.html;wwwroot\pallet-data.html;wwwroot\pallet-directory.html" CopyToOutputDirectory="Never" CopyToPublishDirectory="Never" />
    <None Update="dotnet-tools.json;README.md;App_Data\**\*;Database\**\*" CopyToOutputDirectory="Never" CopyToPublishDirectory="Never" />
  </ItemGroup>
  <PropertyGroup>
    <PublishTrimmed>false</PublishTrimmed>
    <CompressionEnabled>false</CompressionEnabled>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <CopyDebugSymbolFilesFromPackages>false</CopyDebugSymbolFilesFromPackages>
    <CopyDocumentationFilesFromPackages>false</CopyDocumentationFilesFromPackages>
  </PropertyGroup>
  <Target Name="ExcludeWebPublishDebugFiles" AfterTargets="ComputeFilesToPublish" BeforeTargets="GenerateSingleFileBundle">
    <ItemGroup>
      <ResolvedFileToPublish Remove="@(ResolvedFileToPublish)" Condition="'%(ResolvedFileToPublish.Extension)' == '.pdb'" />
      <ResolvedFileToPublish Remove="@(ResolvedFileToPublish)" Condition="'%(ResolvedFileToPublish.Extension)' == '.br' Or '%(ResolvedFileToPublish.Extension)' == '.gz'" />
    </ItemGroup>
  </Target>
</Project>
