<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Scanner.Server.DAL\Scanner.Server.DAL.csproj" />
    <ProjectReference Include="..\Scanner.Server.Model\Scanner.Server.Model.csproj" />
  </ItemGroup>
</Project>
